CREATE TABLE IF NOT EXISTS cashbox_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    operation VARCHAR(20) NOT NULL,
    amount DOUBLE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
