version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: psclubcrm-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command: [
      "-source", "file:///migrations",
      "-database", "mysql://crmuser:crmpass@tcp(db:3306)/psclub?parseTime=true",
      "up"
    ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psclubcrm-backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DSN: ${DSN}
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:4000"
    command: ["./wait-for-mysql.sh", "./app" ]
    volumes:
      - ./config:/app/config
      - ./wait-for-mysql.sh:/app/wait-for-mysql.sh
volumes:
  dbdata:

