server:
  port: 4000

database:
  dsn: "crmuser:crmpass@tcp(db:3306)/psclub?parseTime=true"

auth:
  access_secret: "accesssecret"
  refresh_secret: "refreshsecret"
  access_ttl: 900
  refresh_ttl: 604800
